Добавил класс Calendar.java
MeSeurus/GB_Planner_test pull request #1
Opened 2022-06-28 14:50 UTC by emikhailow

2022-06-29 20:56 UTC, AlexBotya approved these changes

2022-06-30 08:37 UTC, MeSeurus requested changes
Всё хорошо, только поправь packages как договаривались вчера: entities -> entity, services -> service и т.д.

2022-06-30 09:25 UTC, emikhailow commented
> Всё хорошо, только поправь packages как договаривались вчера: entities -> entity, services -> service и т.д.

Сделал

2022-06-30 10:25 UTC, MeSeurus approved these changes

2022-06-30 10:25 UTC, merged